$(document).ready(function() {
    $("#pg1").click(function() {
        $('#pgPic1 h2').css('visibility', 'visible');
        document.getElementById("pp_arrow").style.visibility = "hidden";
        document.getElementById("ppg_arrow").style.visibility = "visible";
        document.getElementById("pg1").style.top = "0";
        document.getElementById("pg1").style.left = "0";
        document.getElementById("pg1").style.width = "100vw";
        document.getElementById("pg1").style.height = "180vw";
        document.getElementById("pg1").style.zIndex = "10";
        document.body.style.position = "fixed";
        $("#ppg_arrow").click(function() {
            $('#pgPic1 h2').css('visibility', 'hidden');
            document.getElementById("pp_arrow").style.visibility = "visible";
            document.getElementById("ppg_arrow").style.visibility = "hidden";
            document.getElementById("pg1").style.top = "14vw";
            document.getElementById("pg1").style.left = "0vw";
            document.getElementById("pg1").style.width = "33vw";
            document.getElementById("pg1").style.height = "33vw";
            document.getElementById("pg1").style.zIndex = "0";
            document.body.style.position = "absolute";
        });
    });
    $("#pg2").click(function() {
         $('#pgPic2 h2').css('visibility', 'visible');
        document.getElementById("pp_arrow").style.visibility = "hidden";
        document.getElementById("ppg_arrow").style.visibility = "visible";
        document.getElementById("pg2").style.top = "0";
        document.getElementById("pg2").style.left = "0";
        document.getElementById("pg2").style.width = "100vw";
        document.getElementById("pg2").style.height = "180vw";
        document.getElementById("pg2").style.zIndex = "10";
        document.body.style.position = "fixed";
         $("#ppg_arrow").click(function() {
            $('#pgPic2 h2').css('visibility', 'hidden');
            document.getElementById("pp_arrow").style.visibility = "visible";
            document.getElementById("ppg_arrow").style.visibility = "hidden";
            document.getElementById("pg2").style.top = "14vw";
            document.getElementById("pg2").style.left = "33.5vw";
            document.getElementById("pg2").style.width = "33vw";
            document.getElementById("pg2").style.height = "33vw";
            document.getElementById("pg2").style.zIndex = "0";
            document.body.style.position = "absolute";
        });
    });
    $("#pg3").click(function() {
         $('#pgPic3 h2').css('visibility', 'visible');
        document.getElementById("pp_arrow").style.visibility = "hidden";
        document.getElementById("ppg_arrow").style.visibility = "visible";
        document.getElementById("pg3").style.top = "0";
        document.getElementById("pg3").style.left = "0";
        document.getElementById("pg3").style.width = "100vw";
        document.getElementById("pg3").style.height = "180vw";
        document.getElementById("pg3").style.zIndex = "10";
        document.body.style.position = "fixed";
         $("#ppg_arrow").click(function() {
            $('#pgPic3 h2').css('visibility', 'hidden');
            document.getElementById("pp_arrow").style.visibility = "visible";
            document.getElementById("ppg_arrow").style.visibility = "hidden";
            document.getElementById("pg3").style.top = "14vw";
            document.getElementById("pg3").style.left = "67vw";
            document.getElementById("pg3").style.width = "33vw";
            document.getElementById("pg3").style.height = "33vw";
            document.getElementById("pg3").style.zIndex = "0";
            document.body.style.position = "absolute";
        });
    });
    $("#pg4").click(function() {
         $('#pgPic4 h2').css('visibility', 'visible');
        document.getElementById("pp_arrow").style.visibility = "hidden";
        document.getElementById("ppg_arrow").style.visibility = "visible";
        document.getElementById("pg4").style.top = "0";
        document.getElementById("pg4").style.left = "0";
        document.getElementById("pg4").style.width = "100vw";
        document.getElementById("pg4").style.height = "180vw";
        document.getElementById("pg4").style.zIndex = "10";
        document.body.style.position = "fixed";
         $("#ppg_arrow").click(function() {
            $('#pgPic4 h2').css('visibility', 'hidden');
            document.getElementById("pp_arrow").style.visibility = "visible";
            document.getElementById("ppg_arrow").style.visibility = "hidden";
            document.getElementById("pg4").style.top = "47.5vw";
            document.getElementById("pg4").style.left = "0";
            document.getElementById("pg4").style.width = "33vw";
            document.getElementById("pg4").style.height = "33vw";
            document.getElementById("pg4").style.zIndex = "0";
            document.body.style.position = "absolute";
        });
    });
    $("#pg5").click(function() {
         $('#pgPic5 h2').css('visibility', 'visible');
        document.getElementById("pp_arrow").style.visibility = "hidden";
        document.getElementById("ppg_arrow").style.visibility = "visible";
        document.getElementById("pg5").style.top = "0";
        document.getElementById("pg5").style.left = "0";
        document.getElementById("pg5").style.width = "100vw";
        document.getElementById("pg5").style.height = "180vw";
        document.getElementById("pg5").style.zIndex = "10";
        document.body.style.position = "fixed";
         $("#ppg_arrow").click(function() {
            $('#pgPic5 h2').css('visibility', 'hidden');
            document.getElementById("pp_arrow").style.visibility = "visible";
            document.getElementById("ppg_arrow").style.visibility = "hidden";
            document.getElementById("pg5").style.top = "47.5vw";
            document.getElementById("pg5").style.left = "33.5vw";
            document.getElementById("pg5").style.width = "33vw";
            document.getElementById("pg5").style.height = "33vw";
            document.getElementById("pg5").style.zIndex = "0";
            document.body.style.position = "absolute";
        });
    });
    $("#pg6").click(function() {
         $('#pgPic6 h2').css('visibility', 'visible');
        document.getElementById("pp_arrow").style.visibility = "hidden";
        document.getElementById("ppg_arrow").style.visibility = "visible";
        document.getElementById("pg6").style.top = "0";
        document.getElementById("pg6").style.left = "0";
        document.getElementById("pg6").style.width = "100vw";
        document.getElementById("pg6").style.height = "180vw";
        document.getElementById("pg6").style.zIndex = "10";
        document.body.style.position = "fixed";
         $("#ppg_arrow").click(function() {
            $('#pgPic6 h2').css('visibility', 'hidden');
            document.getElementById("pp_arrow").style.visibility = "visible";
            document.getElementById("ppg_arrow").style.visibility = "hidden";
            document.getElementById("pg6").style.top = "47.5vw";
            document.getElementById("pg6").style.left = "67vw";
            document.getElementById("pg6").style.width = "33vw";
            document.getElementById("pg6").style.height = "33vw";
            document.getElementById("pg6").style.zIndex = "0";
            document.body.style.position = "absolute";
        });
    });
    $("#pg7").click(function() {
         $('#pgPic7 h2').css('visibility', 'visible');
        document.getElementById("pp_arrow").style.visibility = "hidden";
        document.getElementById("ppg_arrow").style.visibility = "visible";
        document.getElementById("pg7").style.top = "0";
        document.getElementById("pg7").style.left = "0";
        document.getElementById("pg7").style.width = "100vw";
        document.getElementById("pg7").style.height = "180vw";
        document.getElementById("pg7").style.zIndex = "10";
        document.body.style.position = "fixed";
         $("#ppg_arrow").click(function() {
            $('#pgPic7 h2').css('visibility', 'hidden');
            document.getElementById("pp_arrow").style.visibility = "visible";
            document.getElementById("ppg_arrow").style.visibility = "hidden";
            document.getElementById("pg7").style.top = "81vw";
            document.getElementById("pg7").style.left = "0vw";
            document.getElementById("pg7").style.width = "33vw";
            document.getElementById("pg7").style.height = "33vw";
            document.getElementById("pg7").style.zIndex = "0";
            document.body.style.position = "absolute";
        });
    });
    $("#pg8").click(function() {
         $('#pgPic8 h2').css('visibility', 'visible');
        document.getElementById("pp_arrow").style.visibility = "hidden";
        document.getElementById("ppg_arrow").style.visibility = "visible";
        document.getElementById("pg8").style.top = "0";
        document.getElementById("pg8").style.left = "0";
        document.getElementById("pg8").style.width = "100vw";
        document.getElementById("pg8").style.height = "180vw";
        document.getElementById("pg8").style.zIndex = "10";
        document.body.style.position = "fixed";
         $("#ppg_arrow").click(function() {
            $('#pgPic8 h2').css('visibility', 'hidden');
            document.getElementById("pp_arrow").style.visibility = "visible";
            document.getElementById("ppg_arrow").style.visibility = "hidden";
            document.getElementById("pg8").style.top = "81vw";
            document.getElementById("pg8").style.left = "33.5vw";
            document.getElementById("pg8").style.width = "33vw";
            document.getElementById("pg8").style.height = "33vw";
            document.getElementById("pg8").style.zIndex = "0";
            document.body.style.position = "absolute";
        });
    });
    $("#pg9").click(function() {
         $('#pgPic9 h2').css('visibility', 'visible');
        document.getElementById("pp_arrow").style.visibility = "hidden";
        document.getElementById("ppg_arrow").style.visibility = "visible";
        document.getElementById("pg9").style.top = "0";
        document.getElementById("pg9").style.left = "0";
        document.getElementById("pg9").style.width = "100vw";
        document.getElementById("pg9").style.height = "180vw";
        document.getElementById("pg9").style.zIndex = "10";
        document.body.style.position = "fixed";
         $("#ppg_arrow").click(function() {
            $('#pgPic9 h2').css('visibility', 'hidden');
            document.getElementById("pp_arrow").style.visibility = "visible";
            document.getElementById("ppg_arrow").style.visibility = "hidden";
            document.getElementById("pg9").style.top = "81vw";
            document.getElementById("pg9").style.left = "67vw";
            document.getElementById("pg9").style.width = "33vw";
            document.getElementById("pg9").style.height = "33vw";
            document.getElementById("pg9").style.zIndex = "0";
            document.body.style.position = "absolute";
        });
    });
    $("#pg10").click(function() {
         $('#pgPic10 h2').css('visibility', 'visible');
        document.getElementById("pp_arrow").style.visibility = "hidden";
        document.getElementById("ppg_arrow").style.visibility = "visible";
        document.getElementById("pg10").style.top = "0";
        document.getElementById("pg10").style.left = "0";
        document.getElementById("pg10").style.width = "100vw";
        document.getElementById("pg10").style.height = "180vw";
        document.getElementById("pg10").style.zIndex = "10";
        document.body.style.position = "fixed";
         $("#ppg_arrow").click(function() {
            $('#pgPic10 h2').css('visibility', 'hidden');
            document.getElementById("pp_arrow").style.visibility = "visible";
            document.getElementById("ppg_arrow").style.visibility = "hidden";
            document.getElementById("pg10").style.top = "114.5vw";
            document.getElementById("pg10").style.left = "0vw";
            document.getElementById("pg10").style.width = "33vw";
            document.getElementById("pg10").style.height = "33vw";
            document.getElementById("pg10").style.zIndex = "0";
            document.body.style.position = "absolute";
        });
    });
});